// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCypherByDomain(arg1) {
  return window['go']['services']['CredentialService']['DeleteCypherByDomain'](arg1);
}

export function FuzzySearch(arg1, arg2) {
  return window['go']['services']['CredentialService']['FuzzySearch'](arg1, arg2);
}

export function GetCredentialByDomain(arg1) {
  return window['go']['services']['CredentialService']['GetCredentialByDomain'](arg1);
}

export function ListCredential() {
  return window['go']['services']['CredentialService']['ListCredential']();
}

export function SetCredential(arg1) {
  return window['go']['services']['CredentialService']['SetCredential'](arg1);
}
